/-
Copyright (c) 2026 Mizar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mizar
-/

module

public import Mathlib.Analysis.Complex.Circle
public import Mathlib.Topology.ContinuousMap.StoneWeierstrass

/-!
# Uniform approximation on the circle

Integer monomials span a dense complex subspace of continuous circle functions.
-/

@[expose] public section

namespace PseudoPrime.Analysis

/-- The integer monomial p^k as a continuous complex function on the unit circle.
Integer powers are continuous on the circle group and commute with its complex embedding.
These are the test functions for the weighted zero-distribution moments. -/
noncomputable def circleMonomial (k : ℤ) : C(Circle, ℂ) where
  toFun p := (p : ℂ) ^ k
  continuous_toFun := by
    have h :=
      (continuous_subtype_val : Continuous (fun p : Circle => (p : ℂ))).comp
        (continuous_zpow k : Continuous (fun p : Circle => p ^ k))
    change Continuous (fun p : Circle => ((p ^ k : Circle) : ℂ)) at h
    simpa only [Circle.coe_zpow] using h

/-- The degree-zero circle monomial is the constant one function.
Evaluate the zeroth integer power pointwise. This supplies the unit in the monomial algebra. -/
theorem circleMonomial_zero : circleMonomial 0 = 1 := by
  ext p
  exact zpow_zero _

/-- The monomial of degree k+l is the product of those of degrees k and l.
Circle points are nonzero, so integer powers obey the addition rule.
This closes monomials under multiplication. -/
theorem circleMonomial_add (k l : ℤ) :
    circleMonomial (k + l) = circleMonomial k * circleMonomial l := by
  ext p
  exact zpow_add₀ (Circle.coe_ne_zero p) k l

/-- The monomial of negative degree -k is the complex conjugate of that of degree k.
A unit circle point has inverse equal to its conjugate; apply the integer-power rules.
This closes the monomial algebra under conjugation. -/
theorem circleMonomial_neg (k : ℤ) : circleMonomial (-k) = star (circleMonomial k) := by
  ext p
  change (p : ℂ) ^ (-k) = (starRingEnd ℂ) ((p : ℂ) ^ k)
  rw [zpow_neg, ← inv_zpow, Complex.inv_eq_conj (Circle.norm_coe p), map_zpow₀]

/-- The complex star subalgebra generated by all integer circle monomials.
Conjugation sends each generator to its negative-degree generator.
This algebra separates circle points and permits Stone-Weierstrass approximation. -/
noncomputable def circleMonomialAlgebra : StarSubalgebra ℂ C(Circle, ℂ) where
  toSubalgebra := Algebra.adjoin ℂ (Set.range circleMonomial)
  star_mem' := by
    change
      Algebra.adjoin ℂ (Set.range circleMonomial) ≤
        star (Algebra.adjoin ℂ (Set.range circleMonomial))
    apply Algebra.adjoin_le
    rintro f ⟨k, rfl⟩
    exact Algebra.subset_adjoin ⟨-k, circleMonomial_neg k⟩

/-- The underlying complex submodule of the circle monomial algebra is their linear
span. The generators contain one and are closed under multiplication.
Use the adjoin-equals-span criterion. This makes the algebraic approximation a finite
linear combination of the moment test functions. -/
theorem circleMonomialAlgebra_toSubmodule :
    circleMonomialAlgebra.toSubalgebra.toSubmodule =
      Submodule.span ℂ (Set.range circleMonomial) := by
  apply Algebra.adjoin_eq_span_of_subset
  refine Set.Subset.trans ?_ Submodule.subset_span
  intro f hf
  refine Submonoid.closure_induction (fun _ => id) ⟨0, circleMonomial_zero⟩ ?_ hf
  rintro f g hf hg ⟨k, rfl⟩ ⟨l, rfl⟩
  exact ⟨k + l, circleMonomial_add k l⟩

/-- The circle monomial algebra separates distinct circle points.
The degree-one monomial is the injective complex embedding.
This verifies the separation hypothesis of Stone-Weierstrass. -/
theorem circleMonomialAlgebra_separatesPoints : circleMonomialAlgebra.SeparatesPoints := by
  intro p r hpr
  refine ⟨_, ⟨circleMonomial 1, Algebra.subset_adjoin ⟨1, rfl⟩, rfl⟩, ?_⟩
  change (p : ℂ) ^ (1 : ℤ) ≠ (r : ℂ) ^ (1 : ℤ)
  simpa only [zpow_one, ne_eq, Circle.coe_inj] using hpr

/-- The circle monomial star algebra is dense in continuous complex circle functions.
Apply the complex Stone-Weierstrass theorem to its point separation.
This provides uniform approximation by the moment test algebra. -/
theorem circleMonomialAlgebra_closure_eq_top : circleMonomialAlgebra.topologicalClosure = ⊤ :=
  ContinuousMap.starSubalgebra_topologicalClosure_eq_top_of_separatesPoints _
    circleMonomialAlgebra_separatesPoints

/-- The complex linear span of integer circle monomials is dense in continuous circle
functions. Rewrite the monomial algebra as its linear span and transport its closure theorem.
This permits extending bounded functional convergence from all integer moments. -/
theorem span_circleMonomial_closure_eq_top :
    (Submodule.span ℂ (Set.range circleMonomial)).topologicalClosure = ⊤ := by
  rw [← circleMonomialAlgebra_toSubmodule]
  exact
    congrArg (fun A : StarSubalgebra ℂ C(Circle, ℂ) => A.toSubalgebra.toSubmodule)
      circleMonomialAlgebra_closure_eq_top

/-- For a continuous complex circle function and epsilon > 0, a finite linear
combination of integer monomials approximates it within epsilon in supremum norm.
Apply metric closure to the dense span. This supplies quantitative approximation errors
for conductor-normalized zero functionals. -/
theorem exists_circleMonomial_approximation (f : C(Circle, ℂ)) {ε : ℝ} (hε : 0 < ε) :
    ∃ g ∈ Submodule.span ℂ (Set.range circleMonomial), ‖f - g‖ < ε := by
  have h : f ∈ (Submodule.span ℂ (Set.range circleMonomial)).topologicalClosure := by
    rw [span_circleMonomial_closure_eq_top]
    exact Submodule.mem_top
  have hc : f ∈ closure (Submodule.span ℂ (Set.range circleMonomial) : Set C(Circle, ℂ)) := by
    rw [← Submodule.topologicalClosure_coe]
    exact h
  obtain ⟨g, hg, hd⟩ := Metric.mem_closure_iff.mp hc ε hε
  exact ⟨g, hg, by simpa only [dist_eq_norm] using hd⟩

end PseudoPrime.Analysis
