/-
Copyright (c) 2026 Mizar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mizar
-/

module

public import Mathlib.Analysis.SpecialFunctions.Sqrt
public import Mathlib.Tactic

/-! # Rational polynomial majorant for the inverse square root

Generated by `PseudoPrimeWork/tools/gamma_mass_polynomial_certificate.py`.
Exact rational identities and nonnegative Bernstein coefficients prove the
inverse-square-root majorant used in the gamma mass integral.
-/

@[expose] public section

namespace PseudoPrime.Analysis

/-- Rational polynomial majorant for the inverse square root on `[0,1]`.
Expand a degree-ten half-power approximation about the midpoint and add
a rational slack. Bernstein certificates below verify the majorant.
It gives a finite exponential majorant for gamma-kernel mass. -/
noncomputable def invSqrtOneAddPolynomial (z : ℝ) : ℝ :=
  (9674845406880264809 / 9674588160000000000) * z ^ 0 +
    (-1934817422464003 / 3869835264000000) * z ^ 1 +
    (161124788430529 / 429981696000000) * z ^ 2 +
    (-5010400364123 / 16124313600000) * z ^ 3 +
    (8570206442567 / 32248627200000) * z ^ 4 +
    (-2982834188873 / 13436928000000) * z ^ 5 +
    (6816834656863 / 40310784000000) * z ^ 6 +
    (-543746993647 / 5038848000000) * z ^ 7 +
    (69938683529 / 1343692800000) * z ^ 8 +
    (-1984904207 / 120932352000) * z ^ 9 +
    (37713179933 / 15116544000000) * z ^ 10

/-- Signed rational monomial coefficients of the same polynomial.
These coefficients evaluate the finite exponential integral term by term.
Their agreement with the polynomial is certified below. -/
def invSqrtOneAddMonomialCoefficients : List ℚ :=
  [9674845406880264809 / 9674588160000000000, -1934817422464003 / 3869835264000000,
    161124788430529 / 429981696000000, -5010400364123 / 16124313600000,
    8570206442567 / 32248627200000, -2982834188873 / 13436928000000, 6816834656863 / 40310784000000,
    -543746993647 / 5038848000000, 69938683529 / 1343692800000, -1984904207 / 120932352000,
    37713179933 / 15116544000000]

/-- Nonnegative rational Bernstein coefficients of the certified polynomial.
The list records the coefficients including binomial basis factors.
The corresponding identity is checked by rational normalization and ring. -/
private def invSqrtOneAddPositiveCoefficients : List ℚ≥0 :=
  [9674845406880264809 / 9674588160000000000, 9191141051264264059 / 967458816000000000,
    8787999089863527809 / 214990848000000000, 8440367520857441059 / 80621568000000000,
    56948062461403391663 / 322486272000000000, 55048846507578182413 / 268738560000000000,
    53342231590981688663 / 322486272000000000, 7399280128519811059 / 80621568000000000,
    7197541955259684809 / 214990848000000000, 7012251426165836059 / 967458816000000000,
    6841239398565699809 / 9674588160000000000]

/-- Nonnegative rational Bernstein coefficients of the certified polynomial.
The list records the coefficients including binomial basis factors.
The corresponding identity is checked by rational normalization and ring. -/
private def invSqrtOneAddResidualCoefficients : List ℚ≥0 :=
  [4977581419971123609101041963806481 / 93597656065612185600000000000000000000,
    18644265410448125103898895391934597 / 15599609344268697600000000000000000000,
    38076557284487860881733912725505021 / 3119921868853739520000000000000000000,
    184339274565336702799554346400840903 / 2339941401640304640000000000000000000,
    30098548647234619665199444159997953 / 83197916502766387200000000000000000,
    6522927788080353390226142710659044573 / 5199869781422899200000000000000000000,
    13290183984186093525715112989533350267 / 3899902336067174400000000000000000000,
    241586120709261636860294397895559873 / 32499186133893120000000000000000000,
    13764461164453390637511421765244910509 / 1039973956284579840000000000000000000,
    18195323328917949410619891072352275619 / 935976560656121856000000000000000000,
    184906189170564541506713591801351251763 / 7799804672134348800000000000000000000,
    46951027208409413772352391676557942209 / 1949951168033587200000000000000000000,
    190663568990386761364328677989403286909 / 9359765606561218560000000000000000000,
    7441764344958829834238583880546256057 / 519986978142289920000000000000000000,
    431331158415059409908260673181887521 / 51998697814228992000000000000000000,
    956592074067355432547930826193257991 / 243743896004198400000000000000000000,
    15512808919761138475986529423744871477 / 10399739562845798400000000000000000000,
    462369197845787099314422077819969047 / 1039973956284579840000000000000000000,
    936546944258743516253673292555630807 / 9359765606561218560000000000000000000,
    2492368414123937234380640740388029 / 155996093442686976000000000000000000,
    50469434667027093712502651322381907 / 31199218688537395200000000000000000000,
    3728475681485245863766237902636481 / 46798828032806092800000000000000000000]

/-- Evaluate a polynomial in the Bernstein basis using nonnegative rational coefficients.
The list length fixes the degree, and coefficients include binomial basis factors.
This form makes nonnegativity on the unit interval explicit. -/
private noncomputable def nonnegativeBernstein (coefficients : List ℚ≥0) (z : ℝ) : ℝ :=
  ∑ i ∈ Finset.range coefficients.length,
    (coefficients.getD i 0 : ℝ) * z ^ i * (1 - z) ^ (coefficients.length - 1 - i)

/-- On the unit interval each Bernstein basis factor is nonnegative.
Multiply the nonnegative rational coefficient and powers, then sum.
This is the positivity check for the polynomial certificates. -/
private theorem nonnegativeBernstein_nonneg (coefficients : List ℚ≥0) {z : ℝ}
    (hz : z ∈ Set.Icc (0 : ℝ) 1) : 0 ≤ nonnegativeBernstein coefficients z := by
  apply Finset.sum_nonneg
  intro i _
  exact
    mul_nonneg (mul_nonneg (NNRat.cast_nonneg _) (pow_nonneg hz.1 _))
      (pow_nonneg (sub_nonneg.mpr hz.2) _)

/-- The polynomial equals its nonnegative Bernstein expansion.
Exact rational normalization and ring verify the identity at every real argument.
This supplies the sign needed when taking square roots. -/
private theorem invSqrtOneAddPolynomial_positive_identity (z : ℝ) :
    invSqrtOneAddPolynomial z = nonnegativeBernstein invSqrtOneAddPositiveCoefficients z := by
  norm_num only [invSqrtOneAddPolynomial, nonnegativeBernstein, invSqrtOneAddPositiveCoefficients,
    List.length_cons, List.length_nil, Finset.sum_range_succ, Finset.sum_range_zero,
    List.getD_cons_zero, List.getD_cons_succ, NNRat.cast_div, NNRat.cast_ofNat]
  ring

/-- The squared-majorant residual equals its nonnegative Bernstein expansion.
Exact rational normalization and ring verify this degree-twenty-one identity.
Nonnegativity proves the inverse-square-root comparison. -/
private theorem invSqrtOneAddPolynomial_residual_identity (z : ℝ) :
    (1 + z) * invSqrtOneAddPolynomial z ^ 2 - 1 =
      nonnegativeBernstein invSqrtOneAddResidualCoefficients z := by
  norm_num only [invSqrtOneAddPolynomial, nonnegativeBernstein, invSqrtOneAddResidualCoefficients,
    List.length_cons, List.length_nil, Finset.sum_range_succ, Finset.sum_range_zero,
    List.getD_cons_zero, List.getD_cons_succ, NNRat.cast_div, NNRat.cast_ofNat]
  ring

/-- On `[0,1]`, the rational polynomial bounds `1/sqrt(1+z)` from above.
The two Bernstein identities certify its sign and the squared comparison.
Taking square roots and dividing by a positive value proves the bound.
This provides the pointwise input for a gamma-mass integral certificate. -/
theorem inv_sqrt_one_add_le_invSqrtOneAddPolynomial {z : ℝ} (hz : z ∈ Set.Icc (0 : ℝ) 1) :
    1 / Real.sqrt (1 + z) ≤ invSqrtOneAddPolynomial z := by
  have hP : 0 ≤ invSqrtOneAddPolynomial z := by
    rw [invSqrtOneAddPolynomial_positive_identity]
    exact nonnegativeBernstein_nonneg _ hz
  have hQ := nonnegativeBernstein_nonneg invSqrtOneAddResidualCoefficients hz
  rw [← invSqrtOneAddPolynomial_residual_identity] at hQ
  have hsq : 1 ≤ (1 + z) * invSqrtOneAddPolynomial z ^ 2 := by linarith only [hQ]
  have hs := Real.sqrt_le_sqrt hsq
  rw [Real.sqrt_one, Real.sqrt_mul (by linarith only [hz.1] : 0 ≤ 1 + z), Real.sqrt_sq hP] at hs
  apply (div_le_iff₀ (Real.sqrt_pos.mpr (by linarith only [hz.1] : 0 < 1 + z))).mpr
  simpa only [mul_comm] using hs

/-- The polynomial equals the finite sum of its signed monomial coefficients.
Exact rational normalization verifies the coefficient interface.
This form permits termwise integration after exponential substitution. -/
theorem invSqrtOneAddPolynomial_eq_sum (z : ℝ) :
    invSqrtOneAddPolynomial z =
      ∑ i ∈ Finset.range 11, (invSqrtOneAddMonomialCoefficients.getD i 0 : ℝ) * z ^ i := by
  norm_num only [invSqrtOneAddPolynomial, invSqrtOneAddMonomialCoefficients, Finset.sum_range_succ,
    Finset.sum_range_zero, List.getD_cons_zero, List.getD_cons_succ]
  ring

end PseudoPrime.Analysis
