/-
Copyright (c) 2026 Mizar. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mizar
-/

module

public import PseudoPrime.PseudoSquare.Computation.ResidueWheel

/-!
# Small CRT certificates through 1500

Generated by `tools/generate_million_wheel.py`; do not edit by hand.
CRT coverage and residue certificates are checked by Lean at default limits.
-/

@[expose] public section

namespace PseudoPrime.PseudoSquare

/--
The fixed finite set of odd-prime sieve stages `{3, 5}`.
Every listed stage tests whether `jacobiSym n p = 1`; the CRT certificate uses this set
to prove a rejecting stage exists below its cutoff. The definition itself makes no
assumption on the input numerator.
-/
def qNeOneSmall15Primes : Finset ℕ :=
  {3, 5}

/--
If `n < 16`, `n % 30 = 1`, and all stages in `qNeOneSmall15Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 1`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall15_wheel_30_1 {n : ℕ} (hn : n < 16) (hr : n % 30 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall15Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨1, by decide⟩

/--
If `n < 16`, `n % 6 = 1`, and all stages in `qNeOneSmall15Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `5` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall15_wheel_6_1 {n : ℕ} (hn : n < 16) (hr : n % 6 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall15Primes n) : IsSquare n := by
  have hp := qNeOne_residues_5 (hpass 5 (by decide))
  rcases hp with hp | hp
  · exact
      qNeOneSmall15_wheel_30_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
        hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 16 ≤ 19)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 16`, `n % 2 = 1`, and all stages in `qNeOneSmall15Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `3` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall15_wheel_2_1 {n : ℕ} (hn : n < 16) (hr : n % 2 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall15Primes n) : IsSquare n := by
  have hp := qNeOne_residues_3 (hpass 3 (by decide))
  exact
    qNeOneSmall15_wheel_6_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
      hpass

/--
For odd nonsquare `n < 16`, some stage `p` in `qNeOneSmall15Primes` satisfies
`jacobiSym n p ≠ 1`. If every stage passed, the odd-residue coverage theorem would make
`n` a square, contradicting nonsquareness. This is the finite witness-existence interface;
the stage set supplies the concrete candidate primes.
-/
theorem qNeOneSmall15_exists {n : ℕ} (hn : Odd n) (hns : ¬IsSquare n) (hB : n < 16) :
    ∃ p ∈ qNeOneSmall15Primes, jacobiSym n p ≠ 1 := by
  by_contra h
  push Not at h
  exact hns (qNeOneSmall15_wheel_2_1 hB (Nat.odd_iff.mp hn) h)

/--
The fixed finite set of odd-prime sieve stages `{3, 5, 7}`.
Every listed stage tests whether `jacobiSym n p = 1`; the CRT certificate uses this set
to prove a rejecting stage exists below its cutoff. The definition itself makes no
assumption on the input numerator.
-/
def qNeOneSmall63Primes : Finset ℕ :=
  {3, 5, 7}

/--
If `n < 64`, `n % 210 = 1`, and all stages in `qNeOneSmall63Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 1`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall63_wheel_210_1 {n : ℕ} (hn : n < 64) (hr : n % 210 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall63Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨1, by decide⟩

/--
If `n < 64`, `n % 30 = 1`, and all stages in `qNeOneSmall63Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall63_wheel_30_1 {n : ℕ} (hn : n < 64) (hr : n % 30 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall63Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall63_wheel_210_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 64 ≤ 121)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 64 ≤ 151)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 64`, `n % 30 = 19`, and all stages in `qNeOneSmall63Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall63_wheel_30_19 {n : ℕ} (hn : n < 64) (hr : n % 30 = 19)
    (hpass : QNeOneSievePasses qNeOneSmall63Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 64 ≤ 169)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 64 ≤ 79)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 64 ≤ 109)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 64`, `n % 6 = 1`, and all stages in `qNeOneSmall63Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `5` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall63_wheel_6_1 {n : ℕ} (hn : n < 64) (hr : n % 6 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall63Primes n) : IsSquare n := by
  have hp := qNeOne_residues_5 (hpass 5 (by decide))
  rcases hp with hp | hp
  · exact
      qNeOneSmall63_wheel_30_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
        hpass
  · exact
      qNeOneSmall63_wheel_30_19 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 64`, `n % 2 = 1`, and all stages in `qNeOneSmall63Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `3` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall63_wheel_2_1 {n : ℕ} (hn : n < 64) (hr : n % 2 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall63Primes n) : IsSquare n := by
  have hp := qNeOne_residues_3 (hpass 3 (by decide))
  exact
    qNeOneSmall63_wheel_6_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
      hpass

/--
For odd nonsquare `n < 64`, some stage `p` in `qNeOneSmall63Primes` satisfies
`jacobiSym n p ≠ 1`. If every stage passed, the odd-residue coverage theorem would make
`n` a square, contradicting nonsquareness. This is the finite witness-existence interface;
the stage set supplies the concrete candidate primes.
-/
theorem qNeOneSmall63_exists {n : ℕ} (hn : Odd n) (hns : ¬IsSquare n) (hB : n < 64) :
    ∃ p ∈ qNeOneSmall63Primes, jacobiSym n p ≠ 1 := by
  by_contra h
  push Not at h
  exact hns (qNeOneSmall63_wheel_2_1 hB (Nat.odd_iff.mp hn) h)

/--
The fixed finite set of odd-prime sieve stages `{3, 5, 7, 11, 13}`.
Every listed stage tests whether `jacobiSym n p = 1`; the CRT certificate uses this set
to prove a rejecting stage exists below its cutoff. The definition itself makes no
assumption on the input numerator.
-/
def qNeOneSmall750Primes : Finset ℕ :=
  {3, 5, 7, 11, 13}

/--
If `n < 750`, `n % 2310 = 1`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 1`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_1 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨1, by decide⟩

/--
For `n % 13 = 5`, passing every stage in `qNeOneSmall750Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall750_reject_13_5 {n : ℕ} (hr : n % 13 = 5)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 5) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 750`, `n % 2310 = 421`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 421`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_421 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 421)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_5 (by decide) hpass

/--
For `n % 13 = 7`, passing every stage in `qNeOneSmall750Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall750_reject_13_7 {n : ℕ} (hr : n % 13 = 7)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 7) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 750`, `n % 2310 = 631`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 631`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_631 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 631)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_7 (by decide) hpass

/--
If `n < 750`, `n % 210 = 1`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_1 {n : ℕ} (hn : n < 750) (hr : n % 210 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall750_wheel_2310_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_2310_421 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_2310_631 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 841)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1681)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
For `n % 13 = 6`, passing every stage in `qNeOneSmall750Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall750_reject_13_6 {n : ℕ} (hr : n % 13 = 6)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 6) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 750`, `n % 2310 = 331`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 331`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_331 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 331)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_6 (by decide) hpass

/--
If `n < 750`, `n % 210 = 121`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_121 {n : ℕ} (hn : n < 750) (hr : n % 210 = 121)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall750_wheel_2310_331 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 751)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 961)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1171)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 2011)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 750`, `n % 2310 = 361`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 361`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_361 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 361)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨19, by decide⟩

/--
If `n < 750`, `n % 210 = 151`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_151 {n : ℕ} (hn : n < 750) (hr : n % 210 = 151)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 991)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1411)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1621)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1831)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall750_wheel_2310_361 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 750`, `n % 30 = 1`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_30_1 {n : ℕ} (hn : n < 750) (hr : n % 30 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall750_wheel_210_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_210_121 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_210_151 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 750`, `n % 2310 = 169`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 169`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_169 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨13, by decide⟩

/--
For `n % 13 = 2`, passing every stage in `qNeOneSmall750Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall750_reject_13_2 {n : ℕ} (hr : n % 13 = 2)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 2) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 750`, `n % 2310 = 379`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 379`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_379 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 379)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_2 (by decide) hpass

/--
If `n < 750`, `n % 210 = 169`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_169 {n : ℕ} (hn : n < 750) (hr : n % 210 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1849)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 2269)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall750_wheel_2310_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_2310_379 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1219)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 750`, `n % 2310 = 289`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 289`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_289 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 289)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨17, by decide⟩

/--
If `n < 750`, `n % 2310 = 499`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 499`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_499 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 499)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_5 (by decide) hpass

/--
If `n < 750`, `n % 2310 = 709`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 709`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_709 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 709)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall750_reject_13_7 (by decide) hpass

/--
If `n < 750`, `n % 210 = 79`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_79 {n : ℕ} (hn : n < 750) (hr : n % 210 = 79)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 2179)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall750_wheel_2310_289 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_2310_499 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_2310_709 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1549)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 750`, `n % 2310 = 529`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 529`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2310_529 {n : ℕ} (hn : n < 750) (hr : n % 2310 = 529)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨23, by decide⟩

/--
If `n < 750`, `n % 210 = 109`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_210_109 {n : ℕ} (hn : n < 750) (hr : n % 210 = 109)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall750_wheel_2310_529 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 949)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1159)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 1369)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 750 ≤ 2209)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 750`, `n % 30 = 19`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_30_19 {n : ℕ} (hn : n < 750) (hr : n % 30 = 19)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall750_wheel_210_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_210_79 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_210_109 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 750`, `n % 6 = 1`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `5` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_6_1 {n : ℕ} (hn : n < 750) (hr : n % 6 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_5 (hpass 5 (by decide))
  rcases hp with hp | hp
  · exact
      qNeOneSmall750_wheel_30_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall750_wheel_30_19 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 750`, `n % 2 = 1`, and all stages in `qNeOneSmall750Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `3` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall750_wheel_2_1 {n : ℕ} (hn : n < 750) (hr : n % 2 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall750Primes n) : IsSquare n := by
  have hp := qNeOne_residues_3 (hpass 3 (by decide))
  exact
    qNeOneSmall750_wheel_6_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
      hpass

/--
For odd nonsquare `n < 750`, some stage `p` in `qNeOneSmall750Primes` satisfies
`jacobiSym n p ≠ 1`. If every stage passed, the odd-residue coverage theorem would make
`n` a square, contradicting nonsquareness. This is the finite witness-existence interface;
the stage set supplies the concrete candidate primes.
-/
theorem qNeOneSmall750_exists {n : ℕ} (hn : Odd n) (hns : ¬IsSquare n) (hB : n < 750) :
    ∃ p ∈ qNeOneSmall750Primes, jacobiSym n p ≠ 1 := by
  by_contra h
  push Not at h
  exact hns (qNeOneSmall750_wheel_2_1 hB (Nat.odd_iff.mp hn) h)

/--
The fixed finite set of odd-prime sieve stages `{3, 5, 7, 11, 13, 17}`.
Every listed stage tests whether `jacobiSym n p = 1`; the CRT certificate uses this set
to prove a rejecting stage exists below its cutoff. The definition itself makes no
assumption on the input numerator.
-/
def qNeOneSmall1000Primes : Finset ℕ :=
  {3, 5, 7, 11, 13, 17}

/--
If `n < 1000`, `n % 2310 = 1`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 1`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_1 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨1, by decide⟩

/--
For `n % 13 = 5`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_13_5 {n : ℕ} (hr : n % 13 = 5)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 5) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 421`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 421`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_421 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 421)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_5 (by decide) hpass

/--
For `n % 13 = 7`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_13_7 {n : ℕ} (hr : n % 13 = 7)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 7) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 631`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 631`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_631 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 631)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_7 (by decide) hpass

/--
If `n < 1000`, `n % 2310 = 841`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 841`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_841 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 841)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨29, by decide⟩

/--
If `n < 1000`, `n % 210 = 1`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_1 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_2310_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_421 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_631 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_841 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1681)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
For `n % 13 = 6`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_13_6 {n : ℕ} (hr : n % 13 = 6)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 6) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 331`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 331`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_331 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 331)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_6 (by decide) hpass

/--
For `n % 17 = 3`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_17_3 {n : ℕ} (hr : n % 17 = 3)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 3) (hr.trans (by decide)) (by norm_num only)
        (hpass 17 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 751`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 751`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_751 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 751)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_17_3 (by decide) hpass

/--
If `n < 1000`, `n % 2310 = 961`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 961`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_961 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 961)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨31, by decide⟩

/--
If `n < 1000`, `n % 210 = 121`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_121 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 121)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_2310_331 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_751 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_961 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1171)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 2011)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
For `n % 17 = 5`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_17_5 {n : ℕ} (hr : n % 17 = 5)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 5) (hr.trans (by decide)) (by norm_num only)
        (hpass 17 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 991`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 991`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_991 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 991)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_17_5 (by decide) hpass

/--
If `n < 1000`, `n % 2310 = 361`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 361`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_361 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 361)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨19, by decide⟩

/--
If `n < 1000`, `n % 210 = 151`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_151 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 151)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_2310_991 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1411)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1621)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1831)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1000_wheel_2310_361 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1000`, `n % 30 = 1`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_30_1 {n : ℕ} (hn : n < 1000) (hr : n % 30 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_210_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_210_121 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_210_151 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1000`, `n % 2310 = 169`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 169`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_169 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨13, by decide⟩

/--
For `n % 13 = 2`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_13_2 {n : ℕ} (hr : n % 13 = 2)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 2) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 379`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 379`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_379 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 379)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_2 (by decide) hpass

/--
If `n < 1000`, `n % 210 = 169`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_169 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1849)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 2269)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1000_wheel_2310_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_379 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1219)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 289`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 289`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_289 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 289)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨17, by decide⟩

/--
If `n < 1000`, `n % 2310 = 499`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 499`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_499 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 499)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_5 (by decide) hpass

/--
If `n < 1000`, `n % 2310 = 709`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 709`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_709 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 709)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_7 (by decide) hpass

/--
If `n < 1000`, `n % 210 = 79`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_79 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 79)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 2179)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1000_wheel_2310_289 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_499 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_709 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1549)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 529`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 529`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_529 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 529)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨23, by decide⟩

/--
For `n % 13 = 0`, passing every stage in `qNeOneSmall1000Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1000_reject_13_0 {n : ℕ} (hr : n % 13 = 0)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 0) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1000`, `n % 2310 = 949`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 949`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2310_949 {n : ℕ} (hn : n < 1000) (hr : n % 2310 = 949)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1000_reject_13_0 (by decide) hpass

/--
If `n < 1000`, `n % 210 = 109`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_210_109 {n : ℕ} (hn : n < 1000) (hr : n % 210 = 109)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_2310_529 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_2310_949 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1159)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 1369)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1000 ≤ 2209)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 1000`, `n % 30 = 19`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_30_19 {n : ℕ} (hn : n < 1000) (hr : n % 30 = 19)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall1000_wheel_210_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_210_79 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_210_109 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1000`, `n % 6 = 1`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `5` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_6_1 {n : ℕ} (hn : n < 1000) (hr : n % 6 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_5 (hpass 5 (by decide))
  rcases hp with hp | hp
  · exact
      qNeOneSmall1000_wheel_30_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1000_wheel_30_19 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1000`, `n % 2 = 1`, and all stages in `qNeOneSmall1000Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `3` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1000_wheel_2_1 {n : ℕ} (hn : n < 1000) (hr : n % 2 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1000Primes n) : IsSquare n := by
  have hp := qNeOne_residues_3 (hpass 3 (by decide))
  exact
    qNeOneSmall1000_wheel_6_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
      hpass

/--
For odd nonsquare `n < 1000`, some stage `p` in `qNeOneSmall1000Primes` satisfies
`jacobiSym n p ≠ 1`. If every stage passed, the odd-residue coverage theorem would make
`n` a square, contradicting nonsquareness. This is the finite witness-existence interface;
the stage set supplies the concrete candidate primes.
-/
theorem qNeOneSmall1000_exists {n : ℕ} (hn : Odd n) (hns : ¬IsSquare n) (hB : n < 1000) :
    ∃ p ∈ qNeOneSmall1000Primes, jacobiSym n p ≠ 1 := by
  by_contra h
  push Not at h
  exact hns (qNeOneSmall1000_wheel_2_1 hB (Nat.odd_iff.mp hn) h)

/--
The fixed finite set of odd-prime sieve stages `{3, 5, 7, 11, 13, 17, 19}`.
Every listed stage tests whether `jacobiSym n p = 1`; the CRT certificate uses this set
to prove a rejecting stage exists below its cutoff. The definition itself makes no
assumption on the input numerator.
-/
def qNeOneSmall1500Primes : Finset ℕ :=
  {3, 5, 7, 11, 13, 17, 19}

/--
If `n < 1500`, `n % 2310 = 1`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The cutoff forces the unique lift `n = 1`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨1, by decide⟩

/--
For `n % 13 = 5`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_13_5 {n : ℕ} (hr : n % 13 = 5)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 5) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 421`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 421`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_421 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 421)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_5 (by decide) hpass

/--
For `n % 13 = 7`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_13_7 {n : ℕ} (hr : n % 13 = 7)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 7) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 631`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 631`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_631 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 631)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_7 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 841`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 841`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_841 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 841)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨29, by decide⟩

/--
If `n < 1500`, `n % 210 = 1`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_1 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_2310_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_421 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_631 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_841 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 1681)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
For `n % 13 = 6`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_13_6 {n : ℕ} (hr : n % 13 = 6)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 6) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 331`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 331`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_331 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 331)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_6 (by decide) hpass

/--
For `n % 17 = 3`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_17_3 {n : ℕ} (hr : n % 17 = 3)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 3) (hr.trans (by decide)) (by norm_num only)
        (hpass 17 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 751`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 751`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_751 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 751)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_17_3 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 961`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 961`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_961 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 961)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨31, by decide⟩

/--
For `n % 19 = 12`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_19_12 {n : ℕ} (hr : n % 19 = 12)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 12) (hr.trans (by decide)) (by norm_num only)
        (hpass 19 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 1171`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 1171`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1171 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1171)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_19_12 (by decide) hpass

/--
If `n < 1500`, `n % 210 = 121`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_121 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 121)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_2310_331 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_751 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_961 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_1171 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 2011)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
For `n % 17 = 5`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_17_5 {n : ℕ} (hr : n % 17 = 5)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 5) (hr.trans (by decide)) (by norm_num only)
        (hpass 17 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 991`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 991`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_991 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 991)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_17_5 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 1411`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 1411`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1411 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1411)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_7 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 361`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 361`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_361 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 361)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨19, by decide⟩

/--
If `n < 1500`, `n % 210 = 151`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_151 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 151)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_2310_991 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_1411 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 1621)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 1831)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1500_wheel_2310_361 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1500`, `n % 30 = 1`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_30_1 {n : ℕ} (hn : n < 1500) (hr : n % 30 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_210_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_210_121 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_210_151 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1500`, `n % 2310 = 169`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 169`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_169 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨13, by decide⟩

/--
For `n % 13 = 2`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_13_2 {n : ℕ} (hr : n % 13 = 2)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 2) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 379`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 379`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_379 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 379)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_2 (by decide) hpass

/--
For `n % 17 = 12`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_17_12 {n : ℕ} (hr : n % 17 = 12)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 12) (hr.trans (by decide)) (by norm_num only)
        (hpass 17 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 1219`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 1219`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1219 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1219)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_17_12 (by decide) hpass

/--
If `n < 1500`, `n % 210 = 169`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_169 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 169)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 1849)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 2269)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1500_wheel_2310_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_379 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_1219 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1500`, `n % 2310 = 289`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 289`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_289 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 289)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨17, by decide⟩

/--
If `n < 1500`, `n % 2310 = 499`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 499`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_499 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 499)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_5 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 709`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 709`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_709 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 709)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_7 (by decide) hpass

/--
If `n < 1500`, `n % 210 = 79`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_79 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 79)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 2179)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim
  · exact
      qNeOneSmall1500_wheel_2310_289 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_499 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_709 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 1549)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 529`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 529`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_529 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 529)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨23, by decide⟩

/--
For `n % 13 = 0`, passing every stage in `qNeOneSmall1500Primes` is contradictory.
The proof checks that this residue has Jacobi value different from `1`, transports that
value to `n`, and eliminates the contradiction to conclude `IsSquare n`.
This rejecting-residue lemma closes CRT leaves without a size assumption.
-/
theorem qNeOneSmall1500_reject_13_0 {n : ℕ} (hr : n % 13 = 0)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  exact
    (qNeOne_reject_residue (r := 0) (hr.trans (by decide)) (by norm_num only)
        (hpass 13 (by decide))).elim

/--
If `n < 1500`, `n % 2310 = 949`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 949`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_949 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 949)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_0 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 1159`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 1159`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1159 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1159)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact qNeOneSmall1500_reject_13_2 (by decide) hpass

/--
If `n < 1500`, `n % 2310 = 1369`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The cutoff forces the unique lift `n = 1369`; an explicit square root or a rejecting
stage then closes the leaf.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2310_1369 {n : ℕ} (hn : n < 1500) (hr : n % 2310 = 1369)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have heq := qNeOne_unique_lift (Nat.lt_of_lt_of_le hn (by decide)) hr
  subst n
  exact ⟨37, by decide⟩

/--
If `n < 1500`, `n % 210 = 109`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a
square.
The proof classifies passing residues modulo `11` and combines each with the given
class by CRT, then applies the child coverage lemmas or excludes lifts above the cutoff.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_210_109 {n : ℕ} (hn : n < 1500) (hr : n % 210 = 109)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_11 (hpass 11 (by decide))
  rcases hp with hp | hp | hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_2310_529 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_949 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_1159 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_2310_1369 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      (qNeOne_impossible_lift hn (by decide : 1500 ≤ 2209)
          (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))).elim

/--
If `n < 1500`, `n % 30 = 19`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `7` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_30_19 {n : ℕ} (hn : n < 1500) (hr : n % 30 = 19)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_7 (hpass 7 (by decide))
  rcases hp with hp | hp | hp
  · exact
      qNeOneSmall1500_wheel_210_169 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_210_79 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_210_109 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1500`, `n % 6 = 1`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `5` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_6_1 {n : ℕ} (hn : n < 1500) (hr : n % 6 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_5 (hpass 5 (by decide))
  rcases hp with hp | hp
  · exact
      qNeOneSmall1500_wheel_30_1 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass
  · exact
      qNeOneSmall1500_wheel_30_19 hn
        (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide)) hpass

/--
If `n < 1500`, `n % 2 = 1`, and all stages in `qNeOneSmall1500Primes` pass, then `n` is a square.
The proof classifies passing residues modulo `3` and combines each with the given
class by CRT, then applies the child coverage lemmas.
This class-coverage lemma is used by the parent CRT wheel.
-/
theorem qNeOneSmall1500_wheel_2_1 {n : ℕ} (hn : n < 1500) (hr : n % 2 = 1)
    (hpass : QNeOneSievePasses qNeOneSmall1500Primes n) : IsSquare n := by
  have hp := qNeOne_residues_3 (hpass 3 (by decide))
  exact
    qNeOneSmall1500_wheel_6_1 hn (qNeOne_crt (by decide) hr hp (by decide) (by decide) (by decide))
      hpass

/--
For odd nonsquare `n < 1500`, some stage `p` in `qNeOneSmall1500Primes` satisfies
`jacobiSym n p ≠ 1`. If every stage passed, the odd-residue coverage theorem would make
`n` a square, contradicting nonsquareness. This is the finite witness-existence interface;
the stage set supplies the concrete candidate primes.
-/
theorem qNeOneSmall1500_exists {n : ℕ} (hn : Odd n) (hns : ¬IsSquare n) (hB : n < 1500) :
    ∃ p ∈ qNeOneSmall1500Primes, jacobiSym n p ≠ 1 := by
  by_contra h
  push Not at h
  exact hns (qNeOneSmall1500_wheel_2_1 hB (Nat.odd_iff.mp hn) h)

end PseudoPrime.PseudoSquare
